name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - name: Clone intellij-community
        # The branch should stay in sync with what gradle.properties has.
        run: git clone --depth 1 --branch idea/223.8836.41 https://github.com/JetBrains/intellij-community.git ~/intellij-community
      - name: Set IDEA_HOME_PATH
        run: |
          echo "IDEA_HOME_PATH=~/intellij-community" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build
