name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Clone intellij-community
        run: git clone https://github.com/JetBrains/intellij-community.git ~/intellij-community
      - name: Set IDEA_HOME_PATH
        run: |
          echo "IDEA_HOME_PATH=~/intellij-community" >> $GITHUB_ENV
      - name: Set up JDK 1.8
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
